gulp = require('gulp')
stylus = require('gulp-stylus')
cssimport = require('gulp-cssimport')
concat = require('gulp-concat')
plumber = require('gulp-plumber')
notify = require('gulp-notify')
config = require('../config')

gulp.task 'stylesheets', ->
  gulp.src("#{config.appDir}/stylesheets/**/*.styl")
    .pipe(plumber())
    .pipe(stylus(linenos: true).on('error', notify.onError()))
    .pipe(concat('style.css'))
    .pipe(cssimport())
    .pipe(gulp.dest("#{config.publicDir}"))
