gulp = require('gulp')
plumber = require('gulp-plumber')
config = require('./config')
coffee = require('gulp-coffee')
coffeelint = require('gulp-coffeelint')
jsonlint = require('gulp-jsonlint')
livereload = require('gulp-livereload')
notify = require('gulp-notify')

module.exports = ->
  gulp.src('mocks/**/*.json')
    .pipe(jsonlint())
    .pipe(jsonlint.reporter())
  gulp.src("#{config.appDir}/scripts/**/*.coffee")
    .pipe(plumber())
    .pipe(coffeelint())
    .pipe(coffeelint.reporter())
    .pipe(coffee().on('error', notify.onError()))
    .pipe(gulp.dest("#{config.publicDir}/scripts/"))
    # .pipe(livereload())
