gulp = require('gulp')
plumber = require('gulp-plumber')
config = require('./config')
stylus = require('gulp-stylus')
cssimport = require('gulp-cssimport')
concat = require('gulp-concat')
livereload = require('gulp-livereload')
notify = require('gulp-notify')

module.exports = ->
  gulp.src("#{config.appDir}/stylesheets/**/*.styl")
    .pipe(plumber())
    .pipe(stylus(linenos: true).on('error', notify.onError()))
    .pipe(concat('style.css'))
    .pipe(cssimport())
    .pipe(gulp.dest("#{config.publicDir}/stylesheets/"))
    # .pipe(livereload())
